/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author sneth
 */
//importing needed libraries
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

public class SearchStudent extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SearchStudent.class.getName());

    /**
     * Creates new form SearchStudent
     */
    public SearchStudent() {
        initComponents();
        this.setLocationRelativeTo(null);
 //centering our GUI
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SSurname = new javax.swing.JTextField();
        yr = new javax.swing.JLabel();
        Year = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        course = new javax.swing.JComboBox<>();
        Faculty = new javax.swing.JComboBox<>();
        SaveBN = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ClearBN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        SEmail = new javax.swing.JTextField();
        SNumber = new javax.swing.JTextField();
        PhoneNumber = new javax.swing.JTextField();
        SName = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        SSurname1 = new javax.swing.JTextField();
        yr1 = new javax.swing.JLabel();
        Year1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ClearBN1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        menu = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        SEmail1 = new javax.swing.JTextField();
        SNumber1 = new javax.swing.JTextField();
        PhoneNumber1 = new javax.swing.JTextField();
        SName1 = new javax.swing.JTextField();
        faculty = new javax.swing.JTextField();
        course1 = new javax.swing.JTextField();
        SearchBN = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        availability = new javax.swing.JTextField();

        SSurname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSurnameActionPerformed(evt);
            }
        });

        yr.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        yr.setForeground(new java.awt.Color(255, 255, 255));
        yr.setText("Year");

        Year.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 51, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Add Student");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        course.setEditable(true);
        course.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Engineering", "Civil Engineering", "Electrical Engineering", "Mechanical Engineering", "Chemical Engineering", "Industrial Engineering", "Mechatronics Engineering", "Marine Engineering", "Agricultural Management", "Environmental Sciences", "Food Technology", "Horticulture", "Landscape Architecture", "Nature Conservation", "Oceanography", "Sport Management", "Accounting", "Business Administration", "Financial Information Systems", "Hospitality Management", "Tourism Management", "Marketing", "Human Resource Management", "Public Management", "Retail Business Management", "Information Technology", "Computer Science", "Software Development", "Web and Application Development", "Graphic Design", "Multimedia", "Film and Video Technology", "Journalism", "Photography", "Interior Design", "Nursing", "Emergency Medical Care", "Dental Technology", "Medical Laboratory Science", "Somatology", "Environmental Health", "Biomedical Technology", "Radiography", "Education Foundation Phase", "Education Senior Phase", "Social Work", "Youth Development", "Psychology", "Language Practice" }));
        course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseActionPerformed(evt);
            }
        });

        Faculty.setEditable(true);
        Faculty.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Faculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Applied Sciences", "Business & Management Sciences", "Education", "Engineering & the Built Environment", "Health & Wellness Sciences", "Informatics & Design" }));
        Faculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacultyActionPerformed(evt);
            }
        });

        SaveBN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SaveBN.setText("SAVE");
        SaveBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBNActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Faculty");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Student Number");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Course");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Student Email");

        ClearBN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ClearBN.setForeground(new java.awt.Color(255, 0, 51));
        ClearBN.setText("CLEAR");
        ClearBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBNActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("Student Name");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Phone Number");

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 255, 51));
        jButton3.setText("MENU");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Student Surname");

        SEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEmailActionPerformed(evt);
            }
        });

        SNumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SNumberActionPerformed(evt);
            }
        });

        PhoneNumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberActionPerformed(evt);
            }
        });

        SName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SNameActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        SSurname1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SSurname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSurname1ActionPerformed(evt);
            }
        });

        yr1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        yr1.setForeground(new java.awt.Color(255, 255, 255));
        yr1.setText("Year");

        Year1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Year1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Year1ActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 153, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Search Student");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Faculty");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Student Number");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Course");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Student Email");

        ClearBN1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ClearBN1.setForeground(new java.awt.Color(255, 0, 51));
        ClearBN1.setText("CLEAR");
        ClearBN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBN1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(242, 242, 242));
        jLabel16.setText("Student Name");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Phone Number");

        menu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menu.setForeground(new java.awt.Color(0, 255, 51));
        menu.setText("MENU");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Student Surname");

        SEmail1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEmail1ActionPerformed(evt);
            }
        });

        SNumber1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SNumber1ActionPerformed(evt);
            }
        });

        PhoneNumber1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PhoneNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumber1ActionPerformed(evt);
            }
        });

        SName1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SName1ActionPerformed(evt);
            }
        });

        faculty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        faculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyActionPerformed(evt);
            }
        });

        course1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        course1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course1ActionPerformed(evt);
            }
        });

        SearchBN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SearchBN.setText("SEARCH");
        SearchBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBNActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Availability");

        availability.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        availability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availabilityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SNumber1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(SName1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(20, 20, 20)
                        .addComponent(SSurname1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(faculty))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(availability, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 53, Short.MAX_VALUE))
                            .addComponent(SEmail1)
                            .addComponent(PhoneNumber1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yr1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchBN))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ClearBN1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(menu))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(Year1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(course1))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SSurname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(availability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(SEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(PhoneNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(faculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(course1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yr1)
                    .addComponent(Year1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchBN)
                    .addComponent(ClearBN1)
                    .addComponent(menu))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SSurnameActionPerformed

    private void YearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YearActionPerformed

    private void courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseActionPerformed

    private void FacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FacultyActionPerformed

    private void SaveBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBNActionPerformed


    }//GEN-LAST:event_SaveBNActionPerformed

    private void ClearBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBNActionPerformed
 
    }//GEN-LAST:event_ClearBNActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //goes to menu
        this.dispose();
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void SEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SEmailActionPerformed

    private void SNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SNumberActionPerformed

    private void PhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberActionPerformed

    private void SNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SNameActionPerformed

    private void SSurname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSurname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SSurname1ActionPerformed

    private void Year1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Year1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Year1ActionPerformed

    private void ClearBN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBN1ActionPerformed
       //clears everything
        SSurname1.setText("");
        SNumber1.setText("");
        SName1.setText("");
        SEmail1.setText("");
        PhoneNumber1.setText("");
        Year1.setText("");
         faculty.setText("");
         course1.setText("");
        availability.setText("");
        
    }//GEN-LAST:event_ClearBN1ActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
       //goes back to main menu
        this.dispose();
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_menuActionPerformed

    private void SEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEmail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SEmail1ActionPerformed

    private void SNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SNumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SNumber1ActionPerformed

    private void PhoneNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumber1ActionPerformed

    private void SName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SName1ActionPerformed

    private void facultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facultyActionPerformed

    private void course1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course1ActionPerformed

    private void SearchBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBNActionPerformed
                                                                                                                      
    String studentNumber = SNumber1.getText().trim();
    String name = SName1.getText().trim();
    String surname = SSurname1.getText().trim();

    // checks if allthe fields are filled
    if (studentNumber.isEmpty() || name.isEmpty() || surname.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all text fields.", "Input Error", JOptionPane.WARNING_MESSAGE);
        return;
    }

    //searching for student in MySQL
    String sql = "SELECT * FROM students WHERE student_number = ? AND name = ? AND surname = ?";

    try (Connection connect = DatabaseConnection.getConnection();
         PreparedStatement pst = connect.prepareStatement(sql)) {

        pst.setString(1, studentNumber);
        pst.setString(2, name);
        pst.setString(3, surname);

        ResultSet results = pst.executeQuery();

        if (results.next()) {
            // output this in the availability textfield if student is found
            availability.setText("Found");

            //Fills the text fields withe values found in the Database
            course1.setText(results.getString("course"));
            Year1.setText(results.getString("year"));
            faculty.setText(results.getString("faculty"));
            PhoneNumber1.setText(results.getString("phone_number"));
            SEmail1.setText(results.getString("email"));

        }
        else {
            //output for when student is not found
            availability.setText("Not Found");

            //clear the fields that were filled
            course1.setText("");
            Year1.setText("");
            faculty.setText("");
            PhoneNumber1.setText("");
            SEmail1.setText("");
        }

    }//takes care of database errors and tells user why there is an error
    catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }


    }//GEN-LAST:event_SearchBNActionPerformed

    private void availabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availabilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availabilityActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearBN;
    private javax.swing.JButton ClearBN1;
    private javax.swing.JComboBox<String> Faculty;
    private javax.swing.JTextField PhoneNumber;
    private javax.swing.JTextField PhoneNumber1;
    private javax.swing.JTextField SEmail;
    private javax.swing.JTextField SEmail1;
    private javax.swing.JTextField SName;
    private javax.swing.JTextField SName1;
    private javax.swing.JTextField SNumber;
    private javax.swing.JTextField SNumber1;
    private javax.swing.JTextField SSurname;
    private javax.swing.JTextField SSurname1;
    private javax.swing.JButton SaveBN;
    private javax.swing.JButton SearchBN;
    private javax.swing.JTextField Year;
    private javax.swing.JTextField Year1;
    private javax.swing.JTextField availability;
    private javax.swing.JComboBox<String> course;
    private javax.swing.JTextField course1;
    private javax.swing.JTextField faculty;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton menu;
    private javax.swing.JLabel yr;
    private javax.swing.JLabel yr1;
    // End of variables declaration//GEN-END:variables
}
